"""empty message

Revision ID: 1a4f54cf5353
Revises: 
Create Date: 2021-01-24 22:44:40.723970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4f54cf5353'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weatherdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_defined_id', sa.Integer(), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('weather_info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_defined_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weatherdata')
    # ### end Alembic commands ###
